### ISSUE TITLE
replacement of out with pksensi::out 

### ISSUE THREAD

**Issue by mmarikar** [nanhung/pksensi#2]
For the acetaminophen R program in pksensi for windows (10)
system.time(out <- solve_mcsim(x, mName = mName, 
                             params = params,
                             vars = vars,
                             time = times,
                             condition = conditions,
                             generate.infile = F))
                             
 check(out) had to be replaced by pksensi::check(out)
 
 The question is how about for:
 check(out, vars = "lnCPL_APAP_mcgL", SI.cutoff = 0.1, CI.cutoff = 0.1)
 
 Also, for tell2(x,out) what should it be replaced by

**Comment by nanhung** [comment]
Using the same approach.
```r 
pksensi::check(out, vars = "lnCPL_APAP_mcgL", SI.cutoff = 0.1, CI.cutoff = 0.1)
```
You can try to figure out which package make this conflict through `??check` or `check`. It might be a package that had the same function name `check()`.

In addition, you don't need to use `tell(x, out)` anymore. It will execute `tell()` function in `solve_mcsim()` in the new version (v1.1.0).

**Comment by mmarikar** [comment]
worked in windows 10.
Thanks
